// <auto-generated />
using System;
using CarFactory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarFactory.Infrastructure.Migrations
{
    [DbContext(typeof(CarFactoryDbContext))]
    [Migration("20260314142137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarFactory.Domain.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.ProductionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleVIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "EntryDate");

                    b.HasIndex("VehicleVIN", "EntryDate");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SequenceOrder")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CurrentStationId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProductionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VIN");

                    b.HasIndex("CurrentStationId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Year")
                        .IsUnique();

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.VehicleModelPart", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("integer");

                    b.HasKey("VehicleModelId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("VehicleModelParts");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.ProductionLog", b =>
                {
                    b.HasOne("CarFactory.Domain.Entities.Station", "Station")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarFactory.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("VehicleVIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.ProductionOrder", b =>
                {
                    b.HasOne("CarFactory.Domain.Entities.VehicleModel", "Model")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("CarFactory.Domain.Entities.Station", "CurrentStation")
                        .WithMany("Vehicles")
                        .HasForeignKey("CurrentStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CarFactory.Domain.Entities.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentStation");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.VehicleModelPart", b =>
                {
                    b.HasOne("CarFactory.Domain.Entities.Part", "Part")
                        .WithMany("VehicleModelParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarFactory.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("RequiredParts")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.Part", b =>
                {
                    b.Navigation("VehicleModelParts");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.Station", b =>
                {
                    b.Navigation("ProductionLogs");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ProductionLogs");
                });

            modelBuilder.Entity("CarFactory.Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("ProductionOrders");

                    b.Navigation("RequiredParts");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
